# Form implementation generated from reading ui file 'tv.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.volumeUpButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volumeUpButton.setGeometry(QtCore.QRect(180, 300, 131, 28))
        self.volumeUpButton.setObjectName("volumeUpButton")
        self.voluymeDownButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.voluymeDownButton.setGeometry(QtCore.QRect(460, 300, 131, 28))
        self.voluymeDownButton.setObjectName("volumeDownButton")
        self.channelUpButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.channelUpButton.setGeometry(QtCore.QRect(180, 360, 131, 28))
        self.channelUpButton.setObjectName("channelUpButton")
        self.channelDownButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.channelDownButton.setGeometry(QtCore.QRect(470, 370, 131, 28))
        self.channelDownButton.setObjectName("channelDownButton")
        self.muteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.muteButton.setGeometry(QtCore.QRect(340, 430, 93, 28))
        self.muteButton.setObjectName("muteButton")
        self.volumeBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.volumeBar.setGeometry(QtCore.QRect(340, 300, 118, 23))
        self.volumeBar.setProperty("value", 24)
        self.volumeBar.setObjectName("volumeBar")
        self.pix = QtWidgets.QLabel(parent=self.centralwidget)
        self.pix.setGeometry(QtCore.QRect(340, 120, 55, 16))
        self.pix.setObjectName("pix")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.volumeUpButton.setText(_translate("MainWindow", "volume+"))
        self.voluymeDownButton.setText(_translate("MainWindow", "Volume-"))
        self.channelUpButton.setText(_translate("MainWindow", "Next Channel"))
        self.channelDownButton.setText(_translate("MainWindow", "Previous Channel"))
        self.muteButton.setText(_translate("MainWindow", "MUTE"))
        self.pix.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
