# Form implementation generated from reading ui file 'voter.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.voteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.voteButton.setGeometry(QtCore.QRect(290, 250, 93, 28))
        self.voteButton.setObjectName("voteButton")
        self.votinglabel = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.votinglabel.setGeometry(QtCore.QRect(160, 80, 101, 31))
        self.votinglabel.setObjectName("votinglabel")
        self.voterNameInput = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.voterNameInput.setGeometry(QtCore.QRect(290, 80, 211, 21))
        self.voterNameInput.setObjectName("voterNameInput")
        self.numberWhoVoting = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.numberWhoVoting.setGeometry(QtCore.QRect(410, 180, 42, 22))
        self.numberWhoVoting.setObjectName("numberWhoVoting")
        self.whoToVoteFor = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.whoToVoteFor.setGeometry(QtCore.QRect(270, 170, 121, 61))
        self.whoToVoteFor.setObjectName("whoToVoteFor")
        self.resultsSheet = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.resultsSheet.setGeometry(QtCore.QRect(220, 290, 231, 221))
        self.resultsSheet.setObjectName("resultsSheet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.voteButton.setText(_translate("MainWindow", "VOTE"))
        self.votinglabel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Who is voting?: </p></body></html>"))
        self.whoToVoteFor.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pick 1 for Bianca</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">pick 2 for Edward</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">pick 3 for Felecia</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
